// Generated by https://quicktype.io

export interface FacturaSaymir {
  exitoso: boolean;
  mensaje: null;
  factura: Factura;
}

export interface Factura {
  identificacion: string;
  nombreCompleto: string;
  nroFactura: string;
  fechaVencimiento: string;
  estado: string;
  valor: number;
  archivo: string;
}
